# Generated by Django 4.0.5 on 2022-11-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrmApp', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblCustomer',
                'ordering': ['customer_name'],
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.FileField(upload_to='OrmApp/static/documents/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='OrmApp/static/images/'),
        ),
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
    ]
