# Generated by Django 4.0.5 on 2022-11-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrmApp', '0003_customer_alter_movie_file_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
