# Generated by Django 4.0.5 on 2022-11-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrmApp', '0004_delete_movie_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
