# Generated by Django 4.0.5 on 2022-11-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrmApp', '0005_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='tblstudent',
        ),
    ]
